[package]
name = "microasync"
version = "0.2.7"
edition = "2021"
repository = "https://github.com/tudbut/microasync"
license = "MIT"
description = "Very small async runner"
categories = ["no-std", "embedded"]

[dependencies]

[features]
no_std = []
